### Health Check da aplicação
GET http://localhost:8000/health

### Busca todas avaliações
GET http://localhost:8000/api/v1/avaliacoes

### Busca por id
GET http://localhost:8000/api/v1/avaliacoes/{id}

### Busca por id aula
GET http://localhost:8000/api/v1/avaliacoes/aula/{id_aula}

### Busca por query
GET http://localhost:8000/api/v1/avaliacoes?peso=1.5&nome=Teste&grau=2

### Deleta por id
DELETE http://localhost:8000/api/v1/avaliacoes/{id}

### Criar avaliação
POST http://localhost:8000/api/v1/avaliacoes
Content-Type: application/json

{
    "nome": "Teste",
    "peso": 1.5,
    "grau": 2,
    "descricao": "Descrição do teste",
    "questoes": [{
        "enunciado": "Enunciado da questão 1",
        "resposta": "Resposta da questão 1"
    },
    {
        "enunciado": "Enunciado da questão 2",
        "resposta": "Resposta da questão 2"
    }],
    "aulas": [
        "aula1",
        "aula2",
        "aula3"
    ]
}

### Atualiza totalmente a avaliação
PUT http://localhost:8000/api/v1/avaliacoes/{id}
Content-Type: application/json

{
    "peso": 2,
    "nome": "Teste",
    "grau": 1,
    "descricao": "Nova Descrição do teste",
    "questoes": [
        {
        "_id": "5f7bcc402955f215bf3bd957",
        "enunciado": "Enunciado da questão 1",
        "resposta": "Resposta da questão 1"
        }
    ],
        "aulas": [
        "aula1"
    ],
    "__v": 0
}

### Atualiza parcialmente a avaliação
PATCH  http://localhost:8000/api/v1/avaliacoes/{id}
Content-Type: application/json

{
    "peso": 1,
    "nome": "Teste2",
    "aulas": [
        "aula"
    ]
}